name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          $CONDA/bin/conda install anaconda-project
          $CONDA/bin/anaconda-project prepare --env-spec dev
          $CONDA/bin/anaconda-project run install-dev --env-spec dev
      - name: Tests
        run: $CONDA/bin/anaconda-project run run-py-tests --env-spec dev