name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: ["py38", "py39"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} & Insall Dependencies
        run: |
          $CONDA/bin/conda install anaconda-project
          $CONDA/bin/anaconda-project prepare --env-spec ${{ matrix.python-version }}
          $CONDA/bin/anaconda-project run --env-spec ${{ matrix.python-version }} install-dev
      - name: Tests
        run: $CONDA/bin/anaconda-project run --env-spec ${{ matrix.python-version }} run-py-tests-cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: ${{ matrix.python-version }}
          path-to-lcov: coverage.xml
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true