name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: ["py38", "py39"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} & Insall Dependencies
        run: |
          $CONDA/bin/conda install anaconda-project
          $CONDA/bin/anaconda-project prepare --env-spec ${{ matrix.python-version }}
          $CONDA/bin/anaconda-project run --env-spec ${{ matrix.python-version }} install-dev
      - name: Tests
        run: $CONDA/bin/anaconda-project run --env-spec ${{ matrix.python-version }} run-py-tests